---
#
# The network connection profile provides client applications the information about the target
# blockchain network that are necessary for the applications to interact with it. These are all
# knowledge that must be acquired from out-of-band sources. This file provides such a source.
#
name: "pharma tracing"

#
# Any properties with an "x-" prefix will be treated as application-specific, exactly like how naming
# in HTTP headers or swagger properties work. The SDK will simply ignore these fields and leave
# them for the applications to process. This is a mechanism for different components of an application
# to exchange information that are not part of the standard schema described below. In particular,
# the "x-type" property with the "hlfv1" value example below is used by Hyperledger Composer to
# determine the type of Fabric networks (v0.6 vs. v1.0) it needs to work with.
#manu
x-type: "hlfv1"

#
# Describe what the target network is/does.
#
description: "drug tracking  management with certain owner"

#
# Schema version of the content. Used by the SDK to apply the corresponding parsing rules.
#
version: "1.0"

#
# The client section will be added on a per org basis see wsale.yaml and retailer.yaml
#
#client:

#
# [Optional]. But most apps would have this section so that channel objects can be constructed
# based on the content below. If an app is creating channels, then it likely will not need this
# section.
#
channels:
  # name of the channel
  mychannel:
    # Required. list of orderers designated by the application to use for transactions on this
    # channel. This list can be a result of access control ("wsale" can only access "ordererA"), or
    # operational decisions to share loads from applications among the orderers.  The values must
    # be "names" of orgs defined under "organizations/peers"
    orderers:
      - orderer.example.com

    # Required. list of peers from participating orgs
    peers:
      peer0.manu.example.com:
        # [Optional]. will this peer be sent transaction proposals for endorsement? The peer must
        # have the chaincode installed. The app can also use this property to decide which peers
        # to send the chaincode install request. Default: true
        endorsingPeer: false

        # [Optional]. will this peer be sent query proposals? The peer must have the chaincode
        # installed. The app can also use this property to decide which peers to send the
        # chaincode install request. Default: true
        chaincodeQuery: true

        # [Optional]. will this peer be sent query proposals that do not require chaincodes, like
        # queryBlock(), queryTransaction(), etc. Default: true
        ledgerQuery: true

        # [Optional]. will this peer be the target of the SDK's listener registration? All peers can
        # produce events but the app typically only needs to connect to one to listen to events.
        # Default: true
        eventSource: true

      peer0.wsale.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer0.retailer.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: false

      peer0.dist.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: false

    # [Optional]. what chaincodes are expected to exist on this channel? The application can use
    # this information to validate that the target peers are in the expected state by comparing
    # this list with the query results of getInstalledChaincodes() and getInstantiatedChaincodes()
    chaincodes:
      # the format follows the "cannonical name" of chaincodes by fabric code
      - pharma:v2

#
# list of participating organizations in this nmanuetwork
#
organizations:
  wsale:
    mspid: wsaleMSP

    peers:
      - peer0.wsale.example.com

    # [Optional]. Certificate Authorities issue certificates for identification purposes in a Fabric based
    # network. Typically certificates provisioning is done in a separate process outside of the
    # runtime network. Fabric-CA is a special certificate authority that provides a REST APIs for
    # dynamic certificate management (enroll, revoke, re-enroll). The following section is only for
    # Fabric-CA servers.
    certificateAuthorities:
      - ca3.example.com

    # [Optional]. If the application is going to make requests that are reserved to organization
    # administrators, including creating/updating channels, installing/instantiating chaincodes, it
    # must have access to the admin identity rmanuepresented by the private key and signing certificate.
    # Both properties can be the PEM string or local path to the PEM file. Note that this is mainly for
    # convenience in development mode, production systems should not expose sensitive information
    # this way. The SDK should allow applications to set the org admin identity via APIs, and only use
    # this route as an alternative when it exists.
    adminPrivateKey:
      path: /home/saiomkar/fabric-samples/pharma/crypto-config/peerOrganizations/wsale.example.com/users/Admin@wsale.example.com/msp/keystore/8a76ccd792e4b424b1458f6cae409aa0f2f676fd76db3d33be2dd9785c9a46e7_sk
    signedCert:
      path: /home/saiomkar/fabric-samples/pharma/crypto-config/peerOrganizations/wsale.example.com/users/Admin@wsale.example.com/msp/signcerts/Admin@wsale.example.com-cert.pem

  # the profile will contain public information about organizations other than the one it belongs to.
  # These are necessary information to make transaction lifecycles work, including MSP IDs and
  # peers with a public URL to send transaction proposals. The file will not contain private
  # information reserved for members of the organization, such as admin key and certificate,
  # fabric-ca registrar enroll ID and secret, etc.
  retailer:
    mspid: retailerMSP
    peers:
      - peer0.retailer.example.com
    certificateAuthorities:
      - ca2.example.com
    adminPrivateKey:
      path: /home/saiomkar/fabric-samples/pharma/crypto-config/peerOrganizations/retailer.example.com/users/Admin@retailer.example.com/msp/keystore/03a785a0f3279a3b504f4603049d8a9d295c3a878903b24c36b479139b5bcaf3_sk
    signedCert:
      path: /home/saiomkar/fabric-samples/pharma/crypto-config/peerOrganizations/retailer.example.com/users/Admin@retailer.example.com/msp/signcerts/Admin@retailer.example.com-cert.pem

  manu:
    mspid: manuMSP
    peers:
      - peer0.manu.example.com
    certificateAuthorities:
      - ca1.example.com
    adminPrivateKey:
      path: /home/saiomkar/fabric-samples/pharma/crypto-config/peerOrganizations/manu.example.com/users/Admin@manu.example.com/msp/keystore/7125a1ef04fad40a3596448248b3283e53f75e5d3a22e6d6f62ceaefdf218898_sk
    signedCert:
      path: /home/saiomkar/fabric-samples/pharma/crypto-config/peerOrganizations/manu.example.com/users/Admin@manu.example.com/msp/signcerts/Admin@manu.example.com-cert.pem

  dist:
    mspid: distMSP
    peers:
      - peer0.dist.example.com
    certificateAuthorities:
      - ca.example.com
    adminPrivateKey:
      path: /home/saiomkar/fabric-samples/pharma/crypto-config/peerOrganizations/dist.example.com/users/Admin@dist.example.com/msp/keystore/2c75c2a3c0e751ec8678dfd1925a5eb39e55289d1d8acb4c018344f8d12153dd_sk
    signedCert:
      path: /home/saiomkar/fabric-samples/pharma/crypto-config/peerOrganizations/dist.example.com/users/Admin@dist.example.com/msp/signcerts/Admin@dist.example.com-cert.pem



#
# List of orderers to send transaction and channel create/update requests to. For the time
# being only one orderer is needed. If more than one is defined, which one get used by the
# SDK is implementation specific. Consult each SDK's documentation for its handling of orderers.
#
orderers:
  orderer.example.com:
    url: grpcs://localhost:7050

    # these are standard properties defined by the gRPC library
    # they will be passed in as-is to gRPC client constructor
    grpcOptions:
      ssl-target-name-override: orderer.example.com
      grpc-max-send-message-length: 15

    tlsCACerts:
      path: /home/saiomkar/fabric-samples/pharma/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/ca.crt

#
# List of peers to send various requests to, including endorsement, query
# and event listener registration.
#
peers:
  peer0.wsale.example.com:
    # this URL is used to send endorsement and query requests
    url: grpcs://localhost:9051

    # this URL is used to connect the EventHub and registering event listeners
    eventUrl: grpcs://localhost:9053

    grpcOptions:
      ssl-target-name-override: peer0.wsale.example.com
    tlsCACerts:
      path: /home/saiomkar/fabric-samples/pharma/crypto-config/peerOrganizations/wsale.example.com/peers/peer0.wsale.example.com/tls/ca.crt


  peer0.retailer.example.com:
    url: grpcs://localhost:10051
    eventUrl: grpcs://localhost:10053
    grpcOptions:
      ssl-target-name-override: peer0.retailer.example.com
    tlsCACerts:
      path: /home/saiomkar/fabric-samples/pharma/crypto-config/peerOrganizations/retailer.example.com/peers/peer0.retailer.example.com/tls/ca.crt


  peer0.dist.example.com:
    url: grpcs://localhost:7051
    eventUrl: grpcs://localhost:7053
    grpcOptions:
      ssl-target-name-override: peer0.dist.example.com
    tlsCACerts:
      path: /home/saiomkar/fabric-samples/pharma/crypto-config/peerOrganizations/dist.example.com/peers/peer0.dist.example.com/tls/ca.crt



  peer0.manu.example.com:
    url: grpcs://localhost:8051
    eventUrl: grpcs://localhost:8053
    grpcOptions:
      ssl-target-name-override: peer0.manu.example.com
    tlsCACerts:
      path: /home/saiomkar/fabric-samples/pharma/crypto-config/peerOrganizations/manu.example.com/peers/peer0.manu.example.com/tls/ca.crt

 
#__dirname
# Fabric-CA is a special kind of Certificate Authority provided by Hyperledger Fabric which allows
# certificate management to be done via REST APIs. Application may choose to use a standard
# Certificate Authority instead of Fabric-CA, in which case this section would not be specified.
#channel
certificateAuthorities:
  ca3.example.com:
    url: https://localhost:10054
    # the properties specified under this object are passed to the 'http' client verbatim when__dirname
    # making the request to the Fabric-CA server
    httpOptions:
      verify: false
    tlsCACerts:
      path: /home/saiomkar/fabric-samples/pharma/crypto-config/peerOrganizations/wsale.example.com/ca/ca.wsale.example.com-cert.pem

    # Fabric-CA supports dynamic user enrollment via REST APIs. A "root" user, a.k.a registrar, is
    # needed to enroll and invoke new users.
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    # [Optional] The optional name of the CA.
    caName: ca3.example.com

  ca2.example.com:
    url: https://localhost:9054
    httpOptions:
      verify: false
    tlsCACerts:
      path: /home/saiomkar/fabric-samples/pharma/crypto-config/peerOrganizations/retailer.example.com/ca/ca.retailer.example.com-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    # [Optional] The optional name of the CA.
    caName: ca2.example.com


  ca1.example.com:
    url: https://localhost:8054
    httpOptions:
      verify: false
    tlsCACerts:
      path: /home/saiomkar/fabric-samples/pharma/crypto-config/peerOrganizations/manu.example.com/ca/ca.manu.example.com-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    # [Optional] The optional name of the CA.
    caName: ca1.example.com

  ca.example.com:
    url: https://localhost:7054
    httpOptions:
      verify: false
    tlsCACerts:
      path: /home/saiomkar/fabric-samples/pharma/crypto-config/peerOrganizations/dist.example.com/ca/ca.dist.example.com-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    # [Optional] The optional name of the CA.
    caName: ca.example.com
    